# Links and Sources

### Energy Information Administration (EIA)
The U.S. Energy Information Administration (EIA) is a principal agency of the U.S. Federal Statistical System responsible for collecting, analyzing, and disseminating energy information. <br>
https://www.eia.gov/


### Electric Sales, Revenue, and Average Price
https://www.eia.gov/electricity/sales_revenue_price/index.php

### Retail Sales - All (Residential, Commercial, Industrial, Transportation)
https://www.eia.gov/electricity/sales_revenue_price/pdf/table_10.pdf <br>
Gives : City, State, #Customers, # MWhrs, # dollars, Average energy price

### Terminology

Difference between Privately owned utilities, Cooperatives, Municipalities : https://ceateam.com/whats-difference-privately-owned-utilities-cooperatives-municipalities/

# Plan 

1. Get demand data from for all the possible cities in US
2. Get demand data from all other sources (excluding cities) for each state
3. Get the average demand per sq.miles for each state using data from (2)
3. Find a way to see what cities are within a given distance 'd' from any given coordinates
4. The total demand at any given coordinate will be the sum of 
    1. The demand from all the cities included in distance 'd' around it
    2. **The total demand from all other sources calculated using (2)**

In [30]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json
import ast

In [78]:
def coordinates_to_state(lat, lon):
    # Using google maps API
    return state_name

def electricity_demand_within_distance(distance):
    # distance - miles
    # electricity demand - MW
    
    return demand

In [32]:
data = pd.read_excel('dataset_energy_demand.xlsx')
data.columns = data.iloc[1]
data.drop(data.index[0:2], inplace=True)
data.reset_index(drop=True,inplace=True)
data

1,Entity,State,Ownership,Customers (Count),Sales (Megawatthours),Revenues (Thousands Dollars),Average Price (cents/kWh)
0,Alaska Electric Light & Power Co.,AK,Investor Owned,17701,405072,46496.8,11.478651
1,Alaska Power and Telephone Co,AK,Investor Owned,8289,73691,23750,32.229173
2,"Alaska Village Elec Coop, Inc",AK,Cooperative,11512,124689,60171.8,48.257505
3,Chugach Electric Assn Inc,AK,Cooperative,113096,1902625,322098.3,16.929153
4,Golden Valley Elec Assn Inc,AK,Cooperative,47669,1244414,282561.3,22.706374
...,...,...,...,...,...,...,...
1642,Adjustment 2022,VT,Other,33230,442257,71575.1,.
1643,Adjustment 2022,WA,Other,67197,1396093,133891.3,.
1644,Adjustment 2022,WI,Other,184746,3367431,418071.9,.
1645,Adjustment 2022,WV,Other,11160,155580,22923.4,.
1646,Adjustment 2022,WY,Other,50509,1093835,132057.8,.

In [3]:
data['Entity'][data['Ownership']=='Municipal']

6                  Ketchikan Public Utilities
12      Albertville Municipal Utilities Board
18                          City of Andalusia
19                      City of Athens - (AL)
20                 City of Bessemer Utilities
                        ...
1579              Waterloo Light & Water Comm
1580                         Waupun Utilities
1582               Whitehall Electric Utility
1586            Wisconsin Rapids W W & L Comm
1594                  City of Gillette - (WY)
Name: Entity, Length: 455, dtype: object

In [4]:
data['Ownership'].unique()

array(['Investor Owned', 'Cooperative', 'Municipal', 'Federal', nan,
       'State', 'Political Subdivision', 'Retail Energy Provider',
       'Other'], dtype=object)

In [8]:
data['State'].unique()

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
       'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object)

In [13]:

len(data['Entity'].unique())#.head(n)

1308

In [33]:
np.set_printoptions(threshold=np.inf)

n = 1308
count = 0
a = data['Entity'].unique()
for x in a:
    if 'City of' in x:
        print(x)
        count+=1
print(count)

City of Andalusia
City of Athens - (AL)
City of Bessemer Utilities
City of Courtland
City of Dothan - (AL)
City of Florence - (AL)
City of Hartselle
City of Huntsville - (AL)
City of Muscle Shoals
City of Opelika - (AL)
City of Russellville - (AL)
City of Scottsboro
City of Tarrant
City of Troy - (AL)
City of Tuscumbia
City of Benton - (AR)
City of Bentonville - (AR)
City of Hope
City of North Little Rock - (AR)
City of Siloam Springs - (AR)
City of West Memphis - (AR)
City of Mesa - (AZ)
City of Anaheim - (CA)
City of Azusa
City of Burbank Water and Power
City of Colton - (CA)
City of Corona - (CA)
City of Glendale - (CA)
City of Lodi - (CA)
City of Moreno Valley - (CA)
City of Palo Alto - (CA)
City of Pasadena - (CA)
City of Redding - (CA)
City of Riverside - (CA)
City of Roseville - (CA)
City of Santa Clara - (CA)
City of Vernon
City of Colorado Springs - (CO)
City of Fort Collins - (CO)
City of Fort Morgan
City of Fountain
City of Longmont
City of Loveland - (CO)
City of Norwich - (CT)
City of Dover - (DE)
City of Milford - (DE)
City of Newark - (DE)
City of Bartow - (FL)
City of Homestead - (FL)
City of Lake Worth Beach - (FL)
City of Lakeland - (FL)
City of Leesburg - (FL)
City of Ocala
City of Tallahassee - (FL)
City of Winter Park - (FL)
New Smyrna Beach City of
Utility Board of the City of Key West, F
City of Buford
City of Calhoun - (GA)
City of Cartersville - (GA)
City of Chattanooga - (TN)
City of Chickamauga
City of College Park - (GA)
City of Covington - (GA)
City of Douglas
City of East Point - (GA)
City of Griffin - (GA)
City of La Grange - (GA)
City of Lawrenceville - (GA)
City of Marietta - (GA)
City of Sylvania - (GA)
City of Thomasville - (GA)
City of Ames - (IA)
City of Independence - (IA)
City of Maquoketa - (IA)
City of Preston
City of Idaho Falls - (ID)
City of Batavia - (IL)
City of Geneva- (IL)
City of Naperville - (IL)
City of Peru - (IL)
City of Springfield - (IL)
City of St Charles - (IL)
City of Anderson - (IN)
City of Auburn - (IN)
City of Bluffton - (IN)
City of Frankfort - (IN)
City of Greenfield - (IN)
City of Jasper - (IN)
City of Lebanon - (IN)
City of Logansport - (IN)
City of Mishawaka
City of Peru - (IN)
City of Richmond - (IN)
City of Chanute
City of Coffeyville - (KS)
City of Garden City
City of Kansas City - (KS)
City of McPherson - (KS)
City of Winfield - (KS)
City of Bardstown - (KY)
City of Benton - (KY)
City of Berea Municipal Utility
City of Bowling Green - (KY)
City of Frankfort - (KY)
City of Franklin - (KY)
City of Fulton - (KY)
City of Glasgow - (KY)
City of Hickman
City of Hopkinsville
City of Jellico
City of Mayfield Plant Board
City of Murray - (KY)
City of Owensboro - (KY)
City of Paducah - (KY)
City of Russellville - (KY)
City of Alexandria - (LA)
City of Lafayette - (LA)
City of Natchitoches
City of Ruston - (LA)
City of Chicopee - (MA)
City of Holyoke - (MA)
City of Norwood - (MA)
City of Peabody - (MA)
City of Taunton
City of Westfield - (MA)
City of Bay City - (MI)
City of Crystal Falls
City of Gladstone
City of Grand Haven - (MI)
City of Holland
City of Lansing - (MI)
City of Marquette - (MI)
City of Negaunee
City of Norway
City of Sturgis
City of Traverse City - (MI)
City of Zeeland - (MI)
City of Alexandria - (MN)
City of Anoka
City of Austin - (MN)
City of Chaska - (MN)
City of Elk River
City of Lake Crystal - (MN)
City of Marshall - (MN)
City of Moorhead - (MN)
City of Owatonna - (MN)
City of Worthington - (MN)
City of Carthage - (MO)
City of Columbia - (MO)
City of Farmington - (MO)
City of Hannibal - (MO)
City of Independence - (MO)
City of Kirkwood - (MO)
City of Lebanon - (MO)
City of Monett - (MO)
City of Poplar Bluff - (MO)
City of Rolla - (MO)
City of Sikeston - (MO)
City of Aberdeen - (MS)
City of Amory
City of Columbus - (MS)
City of Holly Springs
City of Macon - (MS)
City of New Albany - (MS)
City of Okolona
City of Oxford - (MS)
City of Philadelphia - (MS)
City of Starkville
City of Tupelo - (MS)
City of Water Valley - (MS)
City of West Point - (MS)
City of Albemarle - (NC)
City of Concord - (NC)
City of Elizabeth City - (NC)
City of Gastonia - (NC)
City of Kinston - (NC)
City of Lexington - (NC)
City of Lumberton - (NC)
City of Monroe - (NC)
City of Morganton - (NC)
City of New Bern - (NC)
City of Rocky Mount - (NC)
City of Statesville - (NC)
City of Washington - (NC)
City of Wilson
City of Fremont - (NE)
City of Grand Island - (NE)
City of Hastings - (NE)
City of Lexington - (NE)
City of North Platte
City of South Sioux City
City of Vineland - (NJ)
City of Farmington - (NM)
City of Boulder City - (NV)
City of Plattsburgh - (NY)
City of Bowling Green - (OH)
City of Celina - (OH)
City of Cleveland - (OH)
City of Columbus - (OH)
City of Cuyahoga Falls - (OH)
City of Dover - (OH)
City of Hamilton - (OH)
City of Lebanon - (OH)
City of Niles - (OH)
City of Orrville - (OH)
City of Painesville
City of Piqua - (OH)
City of St Marys - (OH)
City of Wadsworth - (OH)
City of Wapakoneta - (OH)
City of Westerville - (OH)
City of Claremore
City of Edmond - (OK)
City of Ponca City - (OK)
City of Eugene - (OR)
City of Forest Grove
City of McMinnville - (OR)
City of Springfield - (OR)
City of Gaffney - (SC)
City of Newberry - (SC)
City of Orangeburg - (SC)
City of Rock Hill - (SC)
City of Brookings - (SD)
City of Madison - (SD)
City of Pierre - (SD)
City of Volga - (SD)
City of Alcoa Utilities
City of Bristol - (TN)
City of Brownsville
City of Clarksville - (TN)
City of Cleveland - (TN)
City of Clinton - (TN)
City of Cookeville - (TN)
City of Covington - (TN)
City of Dayton - (TN)
City of Dickson
City of Dyersburg
City of Elizabethton - (TN)
City of Etowah
City of Fayetteville
City of Gallatin - (TN)
City of Greeneville - (TN)
City of Harriman - (TN)
City of Humboldt
City of Jackson - (TN)
City of LaFollette
City of Lawrenceburg
City of Lenoir - (TN)
City of Lewisburg - (TN)
City of Lexington - (TN)
City of Memphis - (TN)
City of Milan
City of Morristown - (TN)
City of Mt Pleasant - (TN)
City of Newbern
City of Newport
City of Oak Ridge
City of Paris - (TN)
City of Pulaski - (TN)
City of Ripley - (TN)
City of Rockwood - (TN)
City of Shelbyville - (TN)
City of Smithville - (TN)
City of Sparta
City of Springfield - (TN)
City of Sweetwater
City of Trenton - (TN)
City of Union City
City of Winchester - (TN)
City of Brenham - (TX)
City of Bryan - (TX)
City of College Station - (TX)
City of Denton - (TX)
City of Floresville
City of Garland - (TX)
City of Georgetown - (TX)
City of Greenville - (TX)
City of Lubbock - (TX)
City of New Braunfels - (TX)
City of San Antonio - (TX)
City of San Marcos - (TX)
City of Seguin - (TX)
City of Bountiful
City of Logan - (UT)
City of Murray - (UT)
City of Springville - (UT)
City of St George
City of Danville - (VA)
City of Harrisonburg - (VA)
City of Manassas - (VA)
City of Salem - (VA)
City of Burlington Electric - (VT)
City of Centralia - (WA)
City of Ellensburg - (WA)
City of Port Angeles - (WA)
City of Richland - (WA)
City of Seattle - (WA)
City of Tacoma - (WA)
City of Black River Falls
City of Boscobel - (WI)
City of Columbus - (WI)
City of Cuba City
City of Eagle River - (WI)
City of Evansville
City of Kaukauna
City of Lodi - (WI)
City of Marshfield - (WI)
City of Menasha - (WI)
City of New Holstein - (WI)
City of New Richmond
City of Plymouth - (WI)
City of Richland Center - (WI)
City of River Falls
City of Stoughton - (WI)
City of Sturgeon Bay - (WI)
City of Westby
City of Gillette - (WY)
318

In [44]:
import requests

city = 'Lodi'
country = 'USA'
api_url = 'https://api.api-ninjas.com/v1/geocoding?city={}&country={}'.format(city,country)
response = requests.get(api_url + city, headers={'X-Api-Key': 'MUFmQYBgNJyE/VmlfN+wNA==aPmARELVzoFWzbT0'})
if response.status_code == requests.codes.ok:
    print(response.text)
else:
    print("Error:", response.status_code, response.text)

[{"name": "Lodi", "latitude": 45.3138959, "longitude": 9.503263, "country": "IT", "state": "Lombardy"}, {"name": "Lodi", "latitude": 38.1301968, "longitude": -121.2724473, "country": "US", "state": "California"}, {"name": "Lodi", "latitude": 38.092239500000005, "longitude": -121.38984593366523, "country": "US", "state": "California"}, {"name": "Lodi", "latitude": 40.8823215, "longitude": -74.0831971, "country": "US", "state": "New Jersey"}, {"name": "Town of Lodi", "latitude": 42.6139597, "longitude": -76.8224557, "country": "US", "state": "New York"}]

In [81]:
res = json.loads(response.text)
a = ast.literal_eval(str(res[2]))
a

{'name': 'Lodi',
 'latitude': 38.092239500000005,
 'longitude': -121.38984593366523,
 'country': 'US',
 'state': 'California'}